#!/usr/bin/env python3

"""
gene expression and position files management programm to create
genes Dctionnary file of the N closest Genes
"""

import argparse
import multiepigenomics_3d as me3d
import pandas as pd

parser = argparse.ArgumentParser(description="3D transcription map, main file")
# Positionnal argument containing the 3D coordinate of genes
parser.add_argument("-p", "--positions-file", type=argparse.FileType('r'), help='Path to the file containing the x, y, z coordinates of genes', dest="genePos", metavar="genes_position_file")
#parser.add_argument("-e", "--geneExpression-file", type=argparse.FileType('r'), help='path to the file containing the gene expression ', type=str, dest="geneExpr", metavar="gene_expression_file")
parser.add_argument("outfile", nargs='?', default="-", type=argparse.FileType('w'), metavar='output_file', help="Path to the outputfile of genes Dictionnary (or STDOUT).")
parser.add_argument("-n", "--nb-genes", help="Select the number of the closest genes --DEFAULT = 10", type=int, default=10, dest="nGenes", metavar="no_genes")

args = parser.parse_args()

# CALCULATION OF THE DISTANCE MATRIX
distanceMatrix = me3d.matrix_distance(args.genePos)

#CREATING THE DICTIONNARY WITH PARALLELIZATION
sortedDict = list.pop(me3d.parallelise_sorting_matrix(distanceMatrix))

# TODO: 1. Get the gene expression matirx.
#       2. For each of the n_genes get the gene expression and put them in a data frame. (for paralelisation, take the list of keys form the dict, split it is ncpus chunks and paralelise the process.)
#       3.  For each of the rows in the above data frame (i.e. gene_names as index) you compute the sum of correlations of the first element with all the rests. To paralelise that, follow the same way we did in the parallelise_sorting_matrix.

'''1) Get only the name of the closest gene for each gene
'''
dico_N_closest = {}
for genes_name in sortedDict :
    closest_genes = list(pd.DataFrame(sortedDict[genes_name][1:]).index)
    dico_N_closest[genes_name] = list(closest_genes)

'''2) Reading the gene expression file
'''
gene_expression = pd.read_csv('test_GE_Dist_Miara.tab', sep='\t')
gene_exp = pd.DataFrame(gene_expression)

'''3) Get the correlation Matrix from the gene_expression_file
'''
CORR_MATRIX = me3d.correlation_matrix(gene_exp.transpose())

'''4) Create a dictionnary for the sum of correlation for each gene to the Closest
gene
'''
sum_Corr = {}
for gene , closest_gene in dico_N_closest.items() :
    genePosCor = abs(CORR_MATRIX.loc[gene,closest_gene].sum())
    sum_Corr[gene] = genePosCor

print(sum_Corr)


# TODO: 1. Create a function for each of the 4 Step
#       2. Using argpars
#       3. Finding a function to parralelize ??? 
